export const images = {
  main: require('../assets/images/main.png'),
  infoIcon: require('../assets/images/icons/info-sign.png'),
  refreshIcon: require('../assets/images/icons/refresh.png'),
  rightArrow: require('../assets/images/icons/right-arrow.png'),
  beaufortScale0: require('../assets/images/beaufort/beaufort_scale_0.jpg'),
  beaufortScale1: require('../assets/images/beaufort/beaufort_scale_1.jpg'),
  beaufortScale2: require('../assets/images/beaufort/beaufort_scale_2.jpg'),
  beaufortScale3: require('../assets/images/beaufort/beaufort_scale_3.jpg'),
  beaufortScale4: require('../assets/images/beaufort/beaufort_scale_4.jpg'),
  beaufortScale5: require('../assets/images/beaufort/beaufort_scale_5.jpg'),
  beaufortScale6: require('../assets/images/beaufort/beaufort_scale_6.jpg'),
  beaufortScale7: require('../assets/images/beaufort/beaufort_scale_7.jpg'),
  beaufortScale8: require('../assets/images/beaufort/beaufort_scale_8.jpg'),
  beaufortScale9: require('../assets/images/beaufort/beaufort_scale_9.jpg'),
  beaufortScale10: require('../assets/images/beaufort/beaufort_scale_10.jpg'),
  beaufortScale11: require('../assets/images/beaufort/beaufort_scale_11.jpg'),
  beaufortScale12: require('../assets/images/beaufort/beaufort_scale_12.jpg'),
  recoveryAndroidNotificationsBarSmall: require('../assets/images/recoveryinformation/recovery_android_notifications_bar_small.png'),
  recoveryAndroidUseUsbToSmall: require('../assets/images/recoveryinformation/recovery_android_use_usb_to_small.png'),
  recoveryAndroidAutoPlay: require('../assets/images/recoveryinformation/recovery_android_autoplay.png'),
  recoveryAndroidWindowsExplorer: require('../assets/images/recoveryinformation/recovery_android_windows_explorer.png'),
  bricolor: require('../assets/images/about/bri_color.png'),
  logoboem: require('../assets/images/about/logo_boem.png'),
  tilson: require('../assets/images/about/tilson.jpg'),
};
